### ISSUE TITLE
on Aura Router

### ISSUE THREAD

**Issue by harikt** [mnapoli/minimal-app#1]
Hey , 

Aura.Router have an action where you can place the method name.  https://github.com/auraphp/Aura.Router#adding-a-route

``` php
<?php
// add a simple named route without params
$router->add('home', '/');

// add a simple unnamed route with params
$router->add(null, '/{controller}/{action}/{id}');

// add a named route with an extended specification
$router->add('read', '/blog/read/{id}{format}')
    ->addTokens(array(
        'id'     => '\d+',
        'format' => '(\.[^/]+)?',
    ))
    ->addValues(array(
        'controller' => 'blog',
        'action'     => 'read',
        'format'     => '.html',
    ));
```

You can also add a collection of routes easily :  https://github.com/auraphp/Aura.Router#caching-route-information

``` php
$router->setRoutes($routes);
```

When using dependency injection containers you don't need to use the `RouterFactory` . You could make use of the `Router` object itself. See https://github.com/auraphp/Aura.Router/blob/develop-2/src/RouterFactory.php#L29 

The di configuration of aura https://github.com/auraphp/Aura.Router/blob/develop-2/config/Common.php#L14-L24

**Comment by mnapoli** [comment]
Thanks a bunch!

First time I tried Aura's router and it was late so I did it as fast as possible, but I'll definitely look into all that.

Just regarding this:

> Aura.Router have an action where you can place the method name.

I don't think I'll use it, I like the idea to define a controller by giving a `callable`. The idea is that we could define controllers using closures, à la Silex. Of course it's not ready to work right now in that project, but I will probably do it.

**Comment by harikt** [comment]
> I don't think I'll use it, I like the idea to define a controller by giving a callable. The idea is that we could define controllers using closures, à la Silex.

As I mentioned earlier that is why Aura.Dispatcher stands : You can read about architectural changes where @pmjones has beautifully mentioned how to use Closure and later to move to a full stack controller . https://github.com/auraphp/Aura.Dispatcher#refactoring-to-architecture-changes

I don't know how much time it takes to learn things though. So in that case I feel as PHP-DI can resolve the dependencies for the controller , you need to set the controller values to params as the di getting resolved.

In case you have any questions I am happy to answer with what I know.

Thank you.

**Comment by harikt** [comment]
I think this can be closed for it is not an issue.
